[default]
# functionality
check_setup = n
use_graphein = Y
demo_run = y
graph_type = residue
use_dgcnn = n
one_per_entry = n
use_distance_as_weight = n

# data
tables_dir = /home/lanam/dataset/tables
targets_dir = /home/lanam/dataset/targets
file_list_dir = /home/lanam/dataset/lists
model_dir = /home/lanam/dataset/model
categories_dir = /home/lanam/dataset/categories/demo
# /home/lanam/dataset/categories
visualization_dir = /home/lanam/dataset/visualization

# datasets
pdb_catalytic_dir = # directory containing catalytic protein pdb files
pdb_non_catalytic_dir = # directory containing non-catalytic protein pdb files
pdb_demo_dir = /home/lanam/dataset/pdb/demo
pdb_inference_dir = /home/lanam/dataset/inference_pdb
graph_catalytic_dir = # directory containing catalytic protein graph files
graph_non_catalytic_dir = # directory containing non-catalytic protein graph files
demo_graph_dir= /home/lanam/dataset/graphs/demo
graph_dir = /home/lanam/dataset/graphs/demo
inference_dir = /home/lanam/dataset/inference

# analytics
aas_dir = /home/lanam/dataset/amino_acids
analysis_dir = /home/lanam/dataset/analysis
shap_dir = /home/lanam/dataset/shap